#!/usr/bin/env bash
echo "== delete-objects"

set -e
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1 

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \     
| jq -n '{Objects: [inputs | .[] | {Key: .}]}'

aws s3api delete-objects --bucket $BUCKET_NAME --delete