#!/usr/bin/env bash
echo "== delete-objects"

set -e
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1 

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \     
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json

#코드는 일단 이게 맞는 것 같은데 터미널에서 ./s3_solwhi/bash-scripts/delete-object $DEBUCKET 을 해도 안 됨. 이유 불명