#!/usr/bin/env bash

echo "== listing bucket"

if [ -z "$1" ]; then                                                # '-z $1' checks if the first input variable($1) is empty 
    echo "Please enter a bucket name. eg. ./bucket my-bucket-name"        #print
    exit 1                                                         #stop the if statement immediately
fi                                                                 # the end of if-statement 

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME 
