#!/usr/bin/env bash

#where we'll store the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#creating output folder
mkdir -p $OUTPUT_DIR 

#generating a random nmb to determine how many files to create
NUM_FILE=$((RANDOM % 6+5))

for((i=1; i<=NUM_FILE; i++)); do
    #generating random file name
    FILENAME=$OUTPUT_DIR/file_$i.txt"

    #generate random data and write to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((random % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR