#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

if [ -z "$2" ]; then 
    echo "There needs to be a filename"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

aws s3api put-object \
--bucket $BUCKET_NAME \
--key $FILENAME \
--body $FILENAME

