#!/usr/bin/env bash

echo "== syncing"

set -e

if [ -z "$1" ]; then  
    echo "Enter a bucket name. eg. ./bucket my-bucket-name"        
    exit 1                                                        
fi

if [ -z "$2" ]; then  
    echo "Enter a bucket name. eg. ./bucket my-bucket-name"        
    exit 1                                                        
fi
BUCKET_NAME=$2
FILENAME_PREFIX=$2

#where we'll store the files
OUTPUT_DIR="/tmp/s3_solwhi-bash-scripts"

# remove folder if it exists already
rm -r $OUTPUT_DIR

#creating output folder
mkdir -p $OUTPUT_DIR

NUM_FILE=$((RANDOM % 6+5))

for((i=1; i<=NUM_FILE; i++)); do
    #generating random file name
    FILENAME=$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"

    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((random % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
